name: NPM build

on: push

permissions:
    id-token: write
    contents: write

jobs:
    build_linux:
        name: Build Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
            - run: npm ci --include=dev
            - run: npm run build:linux
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}